<?php

/**
 * Implements hook_theme().
 */
function dut_views_theme($existing, $type, $theme, $path) {
  return [
    'dut_views_theme_suggestions' => [
      'variables' => [
        'suggestions' => []
      ],
    ],
    'dut_views_theme_suggestion' => [
      'variables' => [
        'type' => NULL,
        'link' => NULL,
        'suggestions' => [],
      ],
    ],
    'dut_views_theme_suggestion_theme_template' => [
      'variables' => [
        'type' => NULL,
        'link' => NULL,
        'contents' => [],
      ],
    ],
    'dut_views_theme_suggestions_important' => [
      'variables' => [],
    ],
    'dut_views_theme_suggestions_important_new_id' => [
      'variables' => [],
    ],
    'dut_views_theme_suggestions_rescan_description' => [
      'variables' => [],
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_alter().
 */
function dut_views_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
  if (strpos($hook, 'views_view') !== FALSE && empty($suggestions)) {
    /** @var \Drupal\views\ViewExecutable $view */
    $view = $variables['view'];
    $suggestions = $view->buildThemeFunctions($hook);
    $index = array_search($hook, $suggestions);
    if ($index !== FALSE) {
      unset($suggestions[$index]);
    }

    $suggestions = array_reverse($suggestions);
  }
}
